/* SPDX-License-Identifier: Apache-2.0 */
#include <errno.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "mol/mol.h"

static void mol_patchc_usage(const char* executable) {
  (void)fprintf(stderr,
                "Usage: %s INPUT.molpatch.json OUTPUT.molpatch "
                "[--c-output FILE --symbol IDENTIFIER]\n",
                executable);
}

static int mol_patchc_read(const char* path, char** out_data, size_t* out_size) {
  FILE* file = fopen(path, "rb");
  long length;
  char* data;
  if (file == NULL || fseek(file, 0, SEEK_END) != 0) {
    if (file != NULL) {
      (void)fclose(file);
    }
    return 0;
  }
  length = ftell(file);
  if (length <= 0 || (uint64_t)length > MOL_PATCH_MAX_JSON_SIZE || fseek(file, 0, SEEK_SET) != 0) {
    (void)fclose(file);
    return 0;
  }
  data = (char*)malloc((size_t)length);
  if (data == NULL || fread(data, 1u, (size_t)length, file) != (size_t)length) {
    free(data);
    (void)fclose(file);
    return 0;
  }
  if (fclose(file) != 0) {
    free(data);
    return 0;
  }
  *out_data = data;
  *out_size = (size_t)length;
  return 1;
}

static int mol_patchc_write_binary(const char* path, const uint8_t* data, size_t size) {
  FILE* file = fopen(path, "wb");
  int success;
  if (file == NULL) {
    return 0;
  }
  success = fwrite(data, 1u, size, file) == size;
  success = fclose(file) == 0 && success;
  if (!success) {
    (void)remove(path);
  }
  return success;
}

static int mol_patchc_symbol_is_valid(const char* symbol) {
  if (symbol == NULL || !(symbol[0] == '_' || (symbol[0] >= 'A' && symbol[0] <= 'Z') ||
                          (symbol[0] >= 'a' && symbol[0] <= 'z'))) {
    return 0;
  }
  for (size_t index = 1u; symbol[index] != '\0'; ++index) {
    char value = symbol[index];
    if (!(value == '_' || (value >= 'A' && value <= 'Z') || (value >= 'a' && value <= 'z') ||
          (value >= '0' && value <= '9'))) {
      return 0;
    }
  }
  return 1;
}

static int mol_patchc_write_c(const char* path, const char* symbol, const uint8_t* data,
                              size_t size) {
  FILE* file = fopen(path, "wb");
  int success = 1;
  if (file == NULL) {
    return 0;
  }
  success = fprintf(file,
                    "/* SPDX-License-Identifier: Apache-2.0 */\n"
                    "/* Generated by mol-patchc; do not edit. */\n"
                    "#include <stdint.h>\n\n") >= 0;
  success = success && fprintf(file, "const uint8_t %s[%zu] = {", symbol, size) >= 0;
  for (size_t index = 0u; success && index < size; ++index) {
    success = fprintf(file, "%s0x%02X%s", index % 12u == 0u ? "\n    " : " ", data[index],
                      index + 1u == size ? "" : ",") >= 0;
  }
  success = success &&
            fprintf(file, "\n};\nconst unsigned int %s_size = %zuu;\n", symbol, size) >= 0;
  success = success && fclose(file) == 0;
  if (!success) {
    (void)remove(path);
  }
  return success;
}

int main(int argc, char** argv) {
  const char* c_output = NULL;
  const char* symbol = NULL;
  char* json = NULL;
  size_t json_size = 0u;
  uint8_t binary[MOL_PATCH_BINARY_SIZE];
  size_t binary_size = 0u;
  mol_patch_t patch = {0};
  mol_result_t result;
  if (argc != 3 && argc != 7) {
    mol_patchc_usage(argv[0]);
    return 2;
  }
  if (argc == 7) {
    if (strcmp(argv[3], "--c-output") != 0 || strcmp(argv[5], "--symbol") != 0 ||
        !mol_patchc_symbol_is_valid(argv[6])) {
      mol_patchc_usage(argv[0]);
      return 2;
    }
    c_output = argv[4];
    symbol = argv[6];
  }
  if (!mol_patchc_read(argv[1], &json, &json_size)) {
    (void)fprintf(stderr, "Could not read patch source '%s': %s\n", argv[1], strerror(errno));
    return 1;
  }
  patch.struct_size = (uint32_t)sizeof(patch);
  result = mol_patch_compile_json(json, json_size, &patch);
  free(json);
  if (result != MOL_OK) {
    (void)fprintf(stderr, "Patch schema validation failed: %s\n", mol_result_string(result));
    return 1;
  }
  result = mol_patch_encode(&patch, binary, sizeof(binary), &binary_size);
  if (result != MOL_OK || !mol_patchc_write_binary(argv[2], binary, binary_size) ||
      (c_output != NULL && !mol_patchc_write_c(c_output, symbol, binary, binary_size))) {
    (void)fprintf(stderr, "Could not write compiled patch output\n");
    return 1;
  }
  (void)printf("id_hash=%08x bytes=%zu output=%s\n", patch.preset_id_hash, binary_size, argv[2]);
  return 0;
}
