/* SPDX-License-Identifier: Apache-2.0 */
#ifndef MOL_CAPABILITIES_H_
#define MOL_CAPABILITIES_H_

#include <stdint.h>

typedef uint64_t mol_capability_flags_t;

enum {
  MOL_CAPABILITY_CALLER_MEMORY = UINT64_C(1) << 0u,
  MOL_CAPABILITY_INTERLEAVED_F32 = UINT64_C(1) << 1u,
  MOL_CAPABILITY_PLANAR_F32 = UINT64_C(1) << 2u,
  MOL_CAPABILITY_POLYPHONIC_SYNTH = UINT64_C(1) << 3u,
  MOL_CAPABILITY_SAMPLE_ACCURATE_COMMANDS = UINT64_C(1) << 4u,
  MOL_CAPABILITY_SCALE_LOCK = UINT64_C(1) << 5u,
  MOL_CAPABILITY_CHORD_MODE = UINT64_C(1) << 6u,
  MOL_CAPABILITY_CONTINUOUS_SUSTAIN = UINT64_C(1) << 7u,
  MOL_CAPABILITY_TRANSPORT = UINT64_C(1) << 8u,
  MOL_CAPABILITY_METRONOME = UINT64_C(1) << 9u,
  MOL_CAPABILITY_ARPEGGIATOR = UINT64_C(1) << 10u,
  MOL_CAPABILITY_MONOPHONIC_PORTAMENTO = UINT64_C(1) << 11u,
  MOL_CAPABILITY_BUILTIN_PATCHES = UINT64_C(1) << 12u
};

#endif /* MOL_CAPABILITIES_H_ */
