/* SPDX-License-Identifier: Apache-2.0 */
#ifndef MOL_EFFECTS_PUBLIC_H_
#define MOL_EFFECTS_PUBLIC_H_

#include <stdint.h>

typedef uint32_t mol_parameter_id_t;

enum {
  MOL_PARAMETER_CHORUS_RATE_HZ = 1u,
  MOL_PARAMETER_CHORUS_DEPTH_MS = 2u,
  MOL_PARAMETER_CHORUS_MIX = 3u,
  MOL_PARAMETER_DELAY_TIME_MS = 4u,
  MOL_PARAMETER_DELAY_FEEDBACK = 5u,
  MOL_PARAMETER_DELAY_MIX = 6u,
  MOL_PARAMETER_DELAY_SYNC_BEATS = 7u,
  MOL_PARAMETER_REVERB_PREDELAY_MS = 8u,
  MOL_PARAMETER_REVERB_SIZE = 9u,
  MOL_PARAMETER_REVERB_DAMPING = 10u,
  MOL_PARAMETER_REVERB_MIX = 11u,
  MOL_PARAMETER_LIMITER_CEILING_DB = 12u
};

#define MOL_CHORUS_RATE_MIN_HZ 0.05f
#define MOL_CHORUS_RATE_MAX_HZ 5.0f
#define MOL_CHORUS_DEPTH_MIN_MS 0.1f
#define MOL_CHORUS_DEPTH_MAX_MS 10.0f
#define MOL_DELAY_TIME_MIN_MS 1.0f
#define MOL_DELAY_TIME_MAX_MS 4000.0f
#define MOL_DELAY_FEEDBACK_MAX 0.95f
#define MOL_DELAY_SYNC_MAX_BEATS 4.0f
#define MOL_REVERB_PREDELAY_MAX_MS 60.0f
#define MOL_REVERB_DAMPING_MAX 0.99f
#define MOL_LIMITER_CEILING_MIN_DB -12.0f
#define MOL_LIMITER_CEILING_MAX_DB 0.0f

#endif /* MOL_EFFECTS_PUBLIC_H_ */
