# SPDX-License-Identifier: Apache-2.0
include_guard(GLOBAL)

option(MOL_BUILD_TESTS "Build automated tests" ON)
option(MOL_BUILD_TOOLS "Build command-line tools" ON)
option(MOL_BUILD_DAEMON "Build the headless daemon" OFF)
option(MOL_BUILD_WEB_SERVER "Build the local Web control server" OFF)
option(MOL_ENABLE_MIDI "Enable MIDI adapters" ON)
option(MOL_ENABLE_SAMPLER "Enable the optional sampler" OFF)
option(MOL_ENABLE_CHORUS "Enable chorus processing" ON)
option(MOL_ENABLE_DELAY "Enable delay processing" ON)
option(MOL_ENABLE_REVERB "Enable reverb processing" ON)
option(MOL_ENABLE_ASSERTIONS "Enable internal assertions" ON)
option(MOL_ENABLE_SANITIZERS "Enable supported sanitizers" OFF)
option(MOL_ENABLE_COVERAGE "Enable coverage instrumentation" OFF)
option(MOL_ENABLE_LTO "Enable link-time optimization" OFF)
option(MOL_PROFILE_TINY "Build the Tiny resource profile" OFF)
option(MOL_PROFILE_STANDARD "Build the Standard resource profile" ON)
option(MOL_PROFILE_FULL "Build the Full resource profile" OFF)

set(_mol_profile_count 0)
foreach(_mol_profile MOL_PROFILE_TINY MOL_PROFILE_STANDARD MOL_PROFILE_FULL)
  if(${_mol_profile})
    math(EXPR _mol_profile_count "${_mol_profile_count} + 1")
  endif()
endforeach()

if(NOT _mol_profile_count EQUAL 1)
  message(FATAL_ERROR "Exactly one MOL_PROFILE_TINY, MOL_PROFILE_STANDARD, or MOL_PROFILE_FULL must be ON")
endif()
if(MOL_PROFILE_TINY AND MOL_ENABLE_SAMPLER)
  message(FATAL_ERROR "MOL_ENABLE_SAMPLER is not available in the Tiny profile")
endif()
if(MOL_ENABLE_COVERAGE AND MOL_ENABLE_LTO)
  message(FATAL_ERROR "Coverage instrumentation and LTO cannot be enabled together")
endif()
