# SPDX-License-Identifier: Apache-2.0
include_guard(GLOBAL)

include(CheckIPOSupported)

function(mol_enable_optional_instrumentation target)
  if(MOL_ENABLE_SANITIZERS)
    if(CMAKE_C_COMPILER_ID MATCHES "Clang|GNU")
      target_compile_options(${target} PRIVATE -fno-omit-frame-pointer -fsanitize=address,undefined)
      target_link_options(${target} PRIVATE -fno-omit-frame-pointer -fsanitize=address,undefined)
    else()
      message(FATAL_ERROR "MOL_ENABLE_SANITIZERS requires Clang or GCC")
    endif()
  endif()

  if(MOL_ENABLE_THREAD_SANITIZER)
    if(UNIX AND NOT EMSCRIPTEN AND CMAKE_C_COMPILER_ID MATCHES "Clang|GNU")
      target_compile_options(${target} PRIVATE -fno-omit-frame-pointer -fsanitize=thread)
      target_link_options(${target} PRIVATE -fno-omit-frame-pointer -fsanitize=thread)
    else()
      message(FATAL_ERROR "MOL_ENABLE_THREAD_SANITIZER requires native Clang or GCC on Unix")
    endif()
  endif()

  if(MOL_ENABLE_COVERAGE)
    if(CMAKE_C_COMPILER_ID MATCHES "Clang")
      target_compile_options(${target} PRIVATE -fprofile-instr-generate -fcoverage-mapping)
      target_link_options(${target} PRIVATE -fprofile-instr-generate)
    elseif(CMAKE_C_COMPILER_ID STREQUAL "GNU")
      target_compile_options(${target} PRIVATE --coverage)
      target_link_options(${target} PRIVATE --coverage)
    else()
      message(FATAL_ERROR "MOL_ENABLE_COVERAGE requires Clang or GCC")
    endif()
  endif()

  if(MOL_ENABLE_LTO)
    get_property(_mol_ipo_was_checked GLOBAL PROPERTY MOL_IPO_SUPPORTED SET)
    if(NOT _mol_ipo_was_checked)
      check_ipo_supported(RESULT _mol_ipo_supported OUTPUT _mol_ipo_error)
      set_property(GLOBAL PROPERTY MOL_IPO_SUPPORTED "${_mol_ipo_supported}")
      set_property(GLOBAL PROPERTY MOL_IPO_ERROR "${_mol_ipo_error}")
    else()
      get_property(_mol_ipo_supported GLOBAL PROPERTY MOL_IPO_SUPPORTED)
      get_property(_mol_ipo_error GLOBAL PROPERTY MOL_IPO_ERROR)
    endif()
    if(NOT _mol_ipo_supported)
      message(FATAL_ERROR "LTO is unavailable: ${_mol_ipo_error}")
    endif()
    set_property(TARGET ${target} PROPERTY INTERPROCEDURAL_OPTIMIZATION TRUE)
  endif()
endfunction()
